line-length = 88
target-version = "py312"

# Enable useful rules (pyflakes, pycodestyle, import sorting)
extend-select = ["I"]

[lint]
select = [
    "F",    # Pyflakes
    "E",    # Pycodestyle
    "N",    # pep8-naming
    "D",    # pydocstyle
    "UP",   # pyupgrade
    "I001", # isort
    "S",    # flake8-bandits
    "C4",   # flake8-comprehensions
    "SIM",  # flake8-simplify
    "W"     # warning (not error)
]
# Optional ignores
ignore = [
    "D105", # docstring required for magic methods
    "N806", # non lowercase variable in function
    "D107", # docstring in __init__ (arguments should be in class docstring)
    "D100", # undocumented public module (usually redundant with class docstring)
    "S101",  # Use of asserts
]
preview = true

# Exclusions (data, models, logs)
exclude = [
    "data/",
    "models/",
    "logs/",
    ".venv/",
]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
